LOGS_FOLDER: str = "./tmp/private/logs"

DATE_PATTERN = "YYYYMMDD"
DATETIME_PATTERN = "YYYYMMDD-HHmmss"

WEATHER_BASE_NAME = "WEATHER"

ORCHESTRATOR_LOG_FILENAME_KEY = "ORCHESTRATOR_LOG_FILENAME"
ORCHESTRATOR_LOG_FOLDER_KEY = "ORCHESTRATOR_LOG_FOLDER"

WEATHER_ORCHESTRATOR_LOG_MAPPING = {
    WEATHER_BASE_NAME: {
        ORCHESTRATOR_LOG_FILENAME_KEY: f"LOG_ORCHESTRATOR_{WEATHER_BASE_NAME}_{DATE_PATTERN}.json",
        ORCHESTRATOR_LOG_FOLDER_KEY: f"{LOGS_FOLDER}/ORCHESTRATORS/{WEATHER_BASE_NAME}",
    }
}

APPS_SILVER_FOLDER: str = "/home/site/wwwroot/data"
APPS_SILVER_RAW_FOLDER: str = f"{APPS_SILVER_FOLDER}/raw"
APPS_SILVER_NORMALIZED_FOLDER: str = f"{APPS_SILVER_FOLDER}/normalized"
APPS_SILVER_COMPUTED_FOLDER: str = f"{APPS_SILVER_FOLDER}/computed"

APPS_SILVER_NORMALIZED_FILENAME = "normalized_history.parquet"

ORCHESTRATOR_LOG_MAPPING = {**WEATHER_ORCHESTRATOR_LOG_MAPPING}
