FULL_INGESTION_MODE = "FULL"
INCREMENTAL_INGESTION_MODE = "INC"

ORCHESTRATOR_FUNCTION_NAME_KEY = "ORCHESTRATOR_FUNCTION_NAME_KEY"


AZFN_ORCHESTRATE_INGESTION = "azfn_orchestrate_ingestion"
AZFN_ORCHESTRATOR_STATE_ACTIVITY = "azfn_orchestrator_state_activity"
AZFN_TASK_PREPARE_INGESTION = "azfn_task_prepare_ingestion"
AZFN_TASK_NORMALIZE_METRICS_AND_LOAD_TO_FILESYSTEM = "azfn_task_normalize_metrics_and_load_to_filesystem"
AZFN_TASK_COMPUTE_METRICS_AND_LOAD_TO_DATABASE = "azfn_task_compute_metrics_and_load_to_database"


TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_RUNNING = "RUNNING"

POST_INPUT_FILE_PATHS_KEY = "file_paths"
POST_SOURCE_PROCESSED_FILE_PATHS_KEY = "checkpoint_mark_files"

PAYLOAD_INGESTION_MODE_KEY = "ingestion_mode"
PAYLOAD_INPUT_FILE_PATHS_KEY = "file_paths"
PAYLOAD_REQUEST_ID_KEY = "request_id"
PAYLOAD_BASE_NAME_KEY = "base"
