TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_RUNNING = "RUNNING"
POST_INPUT_FILE_PATHS_KEY = "file_paths"
POST_INPUT_DATABASE_SPECS_KEY = "database_specs"
POST_SOURCE_PROCESSED_FILE_PATHS_KEY = "checkpoint_mark_files"

PAYLOAD_INGESTION_MODE_KEY = "ingestion_mode"
PAYLOAD_INPUT_FILE_PATHS_KEY = "file_paths"
PAYLOAD_INPUT_DATABASE_SPECS_KEY = "database_specs"
PAYLOAD_REQUEST_ID_KEY = "request_id"
PAYLOAD_BASE_NAME_KEY = "base"

ORCHESTRATOR_LOGGING_ACTIVITY = "name"
